/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import AboutUs.AboutFrame;
import Attendance.AttendanceFrame;
import Fees.FeeFrame;
import Gradings.GradingsFrame;
import Student.StudentFrame;
import Teacher.TeacherFrame;

/**
 *
 * @author Sithumini
 */
public class HomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    public HomeJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonstudent = new javax.swing.JButton();
        jButtonTeacher = new javax.swing.JButton();
        jButtonGradings = new javax.swing.JButton();
        feebutton = new javax.swing.JButton();
        jButtonAttendance3 = new javax.swing.JButton();
        jButtonAbout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(129, 129, 209));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(129, 129, 209));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard (1).png"))); // NOI18N
        jLabel3.setText("Dashboard");
        jLabel3.setIconTextGap(20);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 70));

        jLabel1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ASK Information Management System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 480, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 110));

        jPanel4.setBackground(new java.awt.Color(129, 129, 209));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonstudent.setBackground(new java.awt.Color(129, 129, 209));
        jButtonstudent.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButtonstudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/students.png"))); // NOI18N
        jButtonstudent.setText("Student Information");
        jButtonstudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonstudent.setIconTextGap(50);
        jButtonstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonstudentActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 330, 70));

        jButtonTeacher.setBackground(new java.awt.Color(129, 129, 209));
        jButtonTeacher.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButtonTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teacher.png"))); // NOI18N
        jButtonTeacher.setText("Teacher Information");
        jButtonTeacher.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonTeacher.setIconTextGap(50);
        jButtonTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTeacherActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 330, 70));

        jButtonGradings.setBackground(new java.awt.Color(129, 129, 209));
        jButtonGradings.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButtonGradings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/score.png"))); // NOI18N
        jButtonGradings.setText("Gradings");
        jButtonGradings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonGradings.setIconTextGap(50);
        jButtonGradings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGradingsActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonGradings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 330, 70));

        feebutton.setBackground(new java.awt.Color(129, 129, 209));
        feebutton.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        feebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fees.png"))); // NOI18N
        feebutton.setText("Fees");
        feebutton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        feebutton.setIconTextGap(50);
        feebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feebuttonActionPerformed(evt);
            }
        });
        jPanel4.add(feebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 330, 70));

        jButtonAttendance3.setBackground(new java.awt.Color(129, 129, 209));
        jButtonAttendance3.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButtonAttendance3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/attendance.png"))); // NOI18N
        jButtonAttendance3.setText("Attendance");
        jButtonAttendance3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonAttendance3.setIconTextGap(50);
        jButtonAttendance3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAttendance3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonAttendance3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 330, 70));

        jButtonAbout.setBackground(new java.awt.Color(129, 129, 209));
        jButtonAbout.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButtonAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/group.png"))); // NOI18N
        jButtonAbout.setText("About Us");
        jButtonAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonAbout.setIconTextGap(50);
        jButtonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 70));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 330, 420));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gif1.gif"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 570, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonstudentActionPerformed
        this.hide();
        StudentFrame studentObj = new StudentFrame();
        studentObj.show();

        
    }//GEN-LAST:event_jButtonstudentActionPerformed

    private void jButtonTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTeacherActionPerformed
        this.hide();
        TeacherFrame teacherObj = new TeacherFrame();
        teacherObj.show();

        
    }//GEN-LAST:event_jButtonTeacherActionPerformed

    private void jButtonGradingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGradingsActionPerformed
       this.hide();
       GradingsFrame gradingObj = new GradingsFrame();
       gradingObj.show();

        
    }//GEN-LAST:event_jButtonGradingsActionPerformed

    private void jButtonAttendance3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAttendance3ActionPerformed
        this.hide();
        AttendanceFrame attendanceObj = new AttendanceFrame();
        attendanceObj.show();


        
    }//GEN-LAST:event_jButtonAttendance3ActionPerformed

    private void jButtonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutActionPerformed
        this.hide();
        AboutFrame aboutObj = new AboutFrame();
        aboutObj.show();

    }//GEN-LAST:event_jButtonAboutActionPerformed

    private void feebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feebuttonActionPerformed
        this.hide();
        FeeFrame feeObj = new FeeFrame();
        feeObj.show();

        
    }//GEN-LAST:event_feebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton feebutton;
    private javax.swing.JButton jButtonAbout;
    private javax.swing.JButton jButtonAttendance3;
    private javax.swing.JButton jButtonGradings;
    private javax.swing.JButton jButtonTeacher;
    private javax.swing.JButton jButtonstudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
